### ISSUE TITLE
SemVer

### ISSUE THREAD

**Issue by zickgraf** [homalg-project/CapAndHomalg.jl#53]
Is this repo following the SemVer standard (https://semver.org/)? If yes, my commit ebf5d3aa7c26274b8f4825ccbbe2b0f42bc228e6 should have bumped the minor version since it introduced a new feature (item 7. on https://semver.org/), and @kamalsaleh's commit 9dd2cbcb15f44b3e5e2ecc4cb33aa219b5bce258 should have caused a bump of the major version due to being a backwards incompatible change (item 8. on https://semver.org/).

**Comment by mohamed-barakat** [comment]
Starting from now :)

**Comment by zickgraf** [comment]
Okay, perfect :D
