### ISSUE TITLE
Automatically install convenience methods for Julia lists

### ISSUE THREAD

**Issue by zickgraf** [homalg-project/CapAndHomalg.jl#59]
Currently, many packages contain special code for installing convenience methods for GAP operations which accept GAP lists to also accept Julia lists. Instead of doing this in every package separately, I propose that CapAndHomalg.jl should redirect `InstallMethod` (and `InstallOtherMethod` etc.) to a custom function which automatically installs such convenience methods in addition to the original GAP methods.

**Comment by mohamed-barakat** [comment]
This would alter the behavior of `GAP.jl`. I also expect @fingolfin to be against this idea.

**Comment by fingolfin** [comment]
Yeah, I indeed would find that quite problematic.

In the end this boils down to you guys trying to shoehorn GAP into Julia, producing a lot of very un-julia-ish code. I realize it's convenient for you to pretend this way that the two systems, and of course as long as your code does not "taint" other users of GAP.jl, you can do whatever you want; but now some people want to use CapAndHomalg within Oscar, and such a feature would then immediately affect us...

**Comment by zickgraf** [comment]
> but now some people want to use CapAndHomalg within Oscar, and such a feature would then immediately affect us...

I see. We could put this behind a flag which packages can explicitly set at the beginning of `read.g` and reset at the end of it. This way we would not affect other packages.

But I also realize now that it is not clear how to handle lists of lists: We might want to handle them recursively, but then again we might want to have GAP lists of Julia arrays at some point.

So I will close this issue and revisit it should the need arise.
