### ISSUE TITLE
GitHub Action workflows should be updated

### ISSUE THREAD

**Issue by zickgraf** [homalg-project/CapAndHomalg.jl#66]
The workflow runs display a warning:

> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, codecov/codecov-action@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

**Comment by mohamed-barakat** [comment]
@zickgraf: I am not sure if there is more to do.

**Comment by mohamed-barakat** [comment]
@zickgraf: I am not sure if there is more to do.

**Comment by zickgraf** [comment]
> @zickgraf: I am not sure if there is more to do.

Seems fine, the warnings are gone :-)
